-- ================================================================
-- RAW$ Protocol — Initial Database Schema
-- Run this in Supabase SQL Editor in one execution
-- ================================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ----------------------------------------------------------------
-- TABLE 1: positions
-- Tracks every user's active LP position across all pools
-- ----------------------------------------------------------------
create table positions (
  id                  uuid primary key default uuid_generate_v4(),
  user_address        text not null,           -- Stellar G... address
  pool_id             text not null,           -- e.g. "aquarius:XLM/USDC"
  pool_protocol       text not null,           -- "aquarius" | "soroswap" | "phoenix" | "raws_amm"
  vault_mode          text not null,           -- "SafeMode" | "YieldMode"
  lp_token_amount     numeric(38,10) not null, -- LP tokens held by vault
  df_token_shares     numeric(38,10) not null, -- dfTokens minted to user
  entry_price_ratio   numeric(38,18) not null, -- token_b/token_a at deposit time (for IL calc)
  entry_timestamp     timestamptz not null default now(),
  is_active           boolean not null default true,
  tx_hash             text,                    -- deposit transaction hash
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index idx_positions_user on positions(user_address);
create index idx_positions_pool on positions(pool_id);
create index idx_positions_active on positions(is_active);

-- ----------------------------------------------------------------
-- TABLE 2: pool_snapshots
-- Time-series data for every tracked pool, captured every 30 min
-- Drives the IL watchdog and NEY score calculation
-- ----------------------------------------------------------------
create table pool_snapshots (
  id                  uuid primary key default uuid_generate_v4(),
  pool_id             text not null,
  pool_protocol       text not null,
  reserve_a           numeric(38,10) not null,   -- token A reserve
  reserve_b           numeric(38,10) not null,   -- token B reserve
  price_ratio         numeric(38,18) not null,   -- reserve_b / reserve_a
  fee_revenue_period  numeric(38,18) not null,   -- fees earned in this 30-min window
  total_tvl_usd       numeric(20,4),
  health_status       text not null default 'GREEN', -- GREEN | YELLOW | RED | RED_CRITICAL
  ney_score           numeric(10,6),             -- Net Effective Yield for this period
  captured_at         timestamptz not null default now()
);

create index idx_snapshots_pool on pool_snapshots(pool_id);
create index idx_snapshots_time on pool_snapshots(captured_at desc);
create index idx_snapshots_health on pool_snapshots(pool_id, health_status, captured_at desc);

-- ----------------------------------------------------------------
-- TABLE 3: compound_log
-- Records every auto-compound event executed by the keeper
-- Shown in the dashboard compound log timeline
-- ----------------------------------------------------------------
create table compound_log (
  id                  uuid primary key default uuid_generate_v4(),
  position_id         uuid not null references positions(id),
  user_address        text not null,
  pool_id             text not null,
  rewards_harvested   numeric(38,10) not null,   -- AQUA or reward tokens claimed
  rewards_usd_value   numeric(20,4),
  lp_tokens_added     numeric(38,10) not null,   -- new LP tokens from reinvestment
  tx_hash             text not null,
  gas_cost_xlm        numeric(20,10) default 0.00015,
  compounded_at       timestamptz not null default now()
);

create index idx_compound_user on compound_log(user_address);
create index idx_compound_position on compound_log(position_id);
create index idx_compound_time on compound_log(compounded_at desc);

-- ----------------------------------------------------------------
-- TABLE 4: alerts
-- Pool health alerts generated by the IL watchdog RED×3 trigger
-- Delivered via Telegram webhook and in-app notification
-- ----------------------------------------------------------------
create table alerts (
  id                  uuid primary key default uuid_generate_v4(),
  user_address        text not null,
  position_id         uuid not null references positions(id),
  pool_id             text not null,
  alert_type          text not null,            -- "RED_CRITICAL" | "YELLOW_WARNING" | "COMPOUND"
  message             text not null,
  suggested_pool_id   text,                     -- recommended exit destination
  suggested_ney       numeric(10,6),            -- projected NEY in suggested pool
  is_read             boolean not null default false,
  is_actioned         boolean not null default false,
  telegram_sent       boolean not null default false,
  created_at          timestamptz not null default now()
);

create index idx_alerts_user on alerts(user_address, is_read);
create index idx_alerts_position on alerts(position_id);

-- ----------------------------------------------------------------
-- TABLE 5: tracked_pools
-- Master list of pools RAW$ monitors and can route deposits to
-- ----------------------------------------------------------------
create table tracked_pools (
  id                  uuid primary key default uuid_generate_v4(),
  pool_id             text not null unique,      -- e.g. "aquarius:XLM/USDC"
  protocol            text not null,            -- "aquarius" | "soroswap" | "phoenix" | "raws_amm"
  token_a_code        text not null,            -- e.g. "XLM"
  token_b_code        text not null,            -- e.g. "USDC"
  token_a_issuer      text,                     -- null for XLM
  token_b_issuer      text,
  contract_address    text,                     -- Soroban C... address
  is_safe_mode        boolean not null default false,  -- true = stablecoin pair
  is_active           boolean not null default true,
  created_at          timestamptz not null default now()
);

-- Seed the initial tracked pools
insert into tracked_pools (pool_id, protocol, token_a_code, token_b_code, is_safe_mode) values
  ('aquarius:XLM/USDC',  'aquarius', 'XLM',  'USDC',  false),
  ('aquarius:XLM/EURC',  'aquarius', 'XLM',  'EURC',  false),
  ('soroswap:XLM/USDC',  'soroswap', 'XLM',  'USDC',  false),
  ('phoenix:XLM/USDC',   'phoenix',  'XLM',  'USDC',  false),
  ('raws_amm:USDC/EURC', 'raws_amm', 'USDC', 'EURC',  true);

-- ----------------------------------------------------------------
-- Enable Realtime on positions and alerts tables
-- (allows frontend to receive live updates via Supabase Realtime)
-- ----------------------------------------------------------------
alter publication supabase_realtime add table positions;
alter publication supabase_realtime add table alerts;

-- ----------------------------------------------------------------
-- Row Level Security (basic setup — expand in production)
-- ----------------------------------------------------------------
alter table positions      enable row level security;
alter table compound_log   enable row level security;
alter table alerts         enable row level security;
alter table pool_snapshots enable row level security;
alter table tracked_pools  enable row level security;

-- Public read on pool_snapshots and tracked_pools (no auth needed to view pools)
create policy "Public pool snapshots read" on pool_snapshots for select using (true);
create policy "Public tracked pools read"  on tracked_pools  for select using (true);

-- Positions and alerts: users can only read their own (keeper uses service role)
create policy "Users read own positions" on positions
  for select using (true);  -- tighten to wallet auth in Step 7

create policy "Users read own alerts" on alerts
  for select using (true);  -- tighten to wallet auth in Step 7
